//
//  SymbolExtension+Transportation.swift
//  symbol-extension
//
//  Created by otake on 2025/05/07.
//

import Foundation

@available(iOS 18.0, macOS 15.0, *)
public extension SymbolExtension {
    @MainActor struct Transportation {
        static let name: String = "Transportation"
        static let systemImage: String = "car.fill"
        static let list: [SymbolExtension] = [
            airplane,
            airplane_arrival,
            airplane_circle,
            airplane_circle_fill,
            airplane_departure,
            bicycle,
            bicycle_circle,
            bicycle_circle_fill,
            bolt_car,
            bolt_car_circle,
            bolt_car_circle_fill,
            bolt_car_fill,
            bus,
            bus_doubledecker,
            bus_doubledecker_fill,
            bus_fill,
            cablecar,
            cablecar_fill,
            car,
            car_2,
            car_2_fill,
            car_badge_gearshape,
            car_badge_gearshape_fill,
            car_circle,
            car_circle_fill,
            car_ferry,
            car_ferry_fill,
            car_fill,
            car_front_waves_down,
            car_front_waves_down_fill,
            car_front_waves_left_and_right_and_up,
            car_front_waves_left_and_right_and_up_fill,
            car_front_waves_up,
            car_front_waves_up_fill,
            car_rear,
            car_rear_fill,
            ev_charger,
            ev_charger_arrowtriangle_left,
            ev_charger_arrowtriangle_left_fill,
            ev_charger_arrowtriangle_right,
            ev_charger_arrowtriangle_right_fill,
            ev_charger_exclamationmark,
            ev_charger_exclamationmark_fill,
            ev_charger_fill,
            ev_charger_slash,
            ev_charger_slash_fill,
            ferry,
            ferry_fill,
            figure_walk,
            figure_walk_circle,
            figure_walk_circle_fill,
            figure_walk_diamond,
            figure_walk_diamond_fill,
            figure_walk_triangle,
            figure_walk_triangle_fill,
            figure_wave,
            figure_wave_circle,
            figure_wave_circle_fill,
            fuelpump,
            fuelpump_and_filter,
            fuelpump_arrowtriangle_left,
            fuelpump_arrowtriangle_left_fill,
            fuelpump_arrowtriangle_right,
            fuelpump_arrowtriangle_right_fill,
            fuelpump_circle,
            fuelpump_circle_fill,
            fuelpump_exclamationmark,
            fuelpump_exclamationmark_fill,
            fuelpump_fill,
            fuelpump_slash,
            fuelpump_slash_fill,
            lightrail,
            lightrail_fill,
            moped,
            moped_fill,
            motorcycle,
            motorcycle_fill,
            sailboat,
            sailboat_circle,
            sailboat_circle_fill,
            sailboat_fill,
            scooter,
            train_side_front_car,
            train_side_middle_car,
            train_side_rear_car,
            tram,
            tram_circle,
            tram_circle_fill,
            tram_fill,
            tram_fill_tunnel,
            truck_box,
            truck_box_badge_clock,
            truck_box_badge_clock_fill,
            truck_box_fill
        ]
    }
}
