//
//  SymbolExtension+Health.swift
//  symbol-extension
//
//  Created by otake on 2025/05/07.
//

import Foundation

@available(iOS 18.0, macOS 15.0, *)
public extension SymbolExtension {
    @MainActor struct Health {
        static let name: String = "Health"
        static let systemImage: String = "staroflife"
        static let list: [SymbolExtension] = [
            allergens,
            allergens_fill,
            apple_meditate,
            apple_meditate_circle,
            apple_meditate_circle_fill,
            apple_meditate_square_stack,
            apple_meditate_square_stack_fill,
            bandage,
            bandage_fill,
            bed_double,
            bed_double_circle,
            bed_double_circle_fill,
            bed_double_fill,
            bolt_heart,
            bolt_heart_fill,
            brain,
            brain_fill,
            brain_filled_head_profile,
            brain_head_profile,
            brain_head_profile_fill,
            bubbles_and_sparkles,
            bubbles_and_sparkles_fill,
            chart_line_text_clipboard,
            chart_line_text_clipboard_fill,
            cross,
            cross_case,
            cross_case_circle,
            cross_case_circle_fill,
            cross_case_fill,
            cross_circle,
            cross_circle_fill,
            cross_fill,
            cross_vial,
            cross_vial_fill,
            ear,
            ear_badge_checkmark,
            ear_badge_waveform,
            ear_fill,
            ear_trianglebadge_exclamationmark,
            eye,
            eye_circle,
            eye_circle_fill,
            eye_fill,
            eye_slash,
            eye_slash_fill,
            eye_square,
            eye_square_fill,
            eye_trianglebadge_exclamationmark,
            eye_trianglebadge_exclamationmark_fill,
            facemask,
            facemask_fill,
            hearingdevice_and_signal_meter,
            hearingdevice_and_signal_meter_fill,
            hearingdevice_ear,
            hearingdevice_ear_fill,
            heart,
            heart_circle,
            heart_circle_fill,
            heart_fill,
            heart_text_clipboard,
            heart_text_clipboard_fill,
            heart_text_square,
            heart_text_square_fill,
            ivfluid_bag,
            ivfluid_bag_fill,
            list_bullet_clipboard,
            list_bullet_clipboard_fill,
            list_clipboard,
            list_clipboard_fill,
            lungs,
            lungs_fill,
            medical_thermometer,
            medical_thermometer_fill,
            microbe,
            microbe_circle,
            microbe_circle_fill,
            microbe_fill,
            pencil_and_list_clipboard,
            pill,
            pill_circle,
            pill_circle_fill,
            pill_fill,
            pills,
            pills_circle,
            pills_circle_fill,
            pills_fill,
            staroflife,
            staroflife_circle,
            staroflife_circle_fill,
            staroflife_fill,
            stethoscope,
            stethoscope_circle,
            stethoscope_circle_fill,
            syringe,
            syringe_fill,
            thermometer_variable,
            thermometer_variable_and_figure,
            thermometer_variable_and_figure_circle,
            thermometer_variable_and_figure_circle_fill,
            vial_viewfinder,
            waveform_path_ecg,
            waveform_path_ecg_rectangle,
            waveform_path_ecg_rectangle_fill
        ]
    }
}
