//
//  SymbolExtension+Connectivity.swift
//  symbol-extension
//
//  Created by otake on 2025/05/07.
//

import Foundation

@available(iOS 18.0, macOS 15.0, *)
public extension SymbolExtension {
    @MainActor struct Connectivity {
        static let name: String = "Connectivity"
        static let systemImage: String = "antenna.radiowaves.left.and.right"
        static let list: [SymbolExtension] = [
            antenna_radiowaves_left_and_right,
            antenna_radiowaves_left_and_right_circle,
            antenna_radiowaves_left_and_right_circle_fill,
            antenna_radiowaves_left_and_right_slash,
            antenna_radiowaves_left_and_right_slash_circle,
            antenna_radiowaves_left_and_right_slash_circle_fill,
            arrow_trianglehead_2_clockwise_rotate_90_icloud,
            arrow_trianglehead_2_clockwise_rotate_90_icloud_fill,
            arrow_trianglehead_clockwise_icloud,
            arrow_trianglehead_clockwise_icloud_fill,
            arrow_trianglehead_counterclockwise_icloud,
            arrow_trianglehead_counterclockwise_icloud_fill,
            bolt_horizontal,
            bolt_horizontal_circle,
            bolt_horizontal_circle_fill,
            bolt_horizontal_fill,
            bolt_horizontal_icloud,
            bolt_horizontal_icloud_fill,
            bonjour,
            cellularbars,
            chart_bar,
            chart_bar_fill,
            checkmark_icloud,
            checkmark_icloud_fill,
            dot_radiowaves_forward,
            dot_radiowaves_left_and_right,
            dot_radiowaves_right,
            dot_radiowaves_up_forward,
            exclamationmark_icloud,
            exclamationmark_icloud_fill,
            externaldrive_connected_to_line_below,
            externaldrive_connected_to_line_below_fill,
            icloud,
            icloud_and_arrow_down,
            icloud_and_arrow_down_fill,
            icloud_and_arrow_up,
            icloud_and_arrow_up_fill,
            icloud_circle,
            icloud_circle_fill,
            icloud_fill,
            icloud_slash,
            icloud_slash_fill,
            icloud_square,
            icloud_square_fill,
            key_icloud,
            key_icloud_fill,
            link_icloud,
            link_icloud_fill,
            lock_icloud,
            lock_icloud_fill,
            network,
            network_badge_shield_half_filled,
            network_slash,
            person_icloud,
            person_icloud_fill,
            personalhotspot,
            personalhotspot_circle,
            personalhotspot_circle_fill,
            personalhotspot_slash,
            wave_3_backward,
            wave_3_backward_circle,
            wave_3_backward_circle_fill,
            wave_3_down,
            wave_3_down_circle,
            wave_3_down_circle_fill,
            wave_3_forward,
            wave_3_forward_circle,
            wave_3_forward_circle_fill,
            wave_3_left,
            wave_3_left_circle,
            wave_3_left_circle_fill,
            wave_3_right,
            wave_3_right_circle,
            wave_3_right_circle_fill,
            wave_3_up,
            wave_3_up_circle,
            wave_3_up_circle_fill,
            wifi,
            wifi_circle,
            wifi_circle_fill,
            wifi_exclamationmark,
            wifi_exclamationmark_circle,
            wifi_exclamationmark_circle_fill,
            wifi_slash,
            wifi_square,
            wifi_square_fill,
            xmark_icloud,
            xmark_icloud_fill
        ]
    }
}
