//
//  SymbolExtension+Media.swift
//  symbol-extension
//
//  Created by otake on 2025/05/07.
//

import Foundation

@available(iOS 18.0, macOS 15.0, *)
public extension SymbolExtension {
    @MainActor struct Media {
        static let name: String = "Media"
        static let systemImage: String = "playpause"
        static let list: [SymbolExtension] = [
            _5_arrow_trianglehead_clockwise,
            _5_arrow_trianglehead_counterclockwise,
            _10_arrow_trianglehead_clockwise,
            _10_arrow_trianglehead_counterclockwise,
            _15_arrow_trianglehead_clockwise,
            _15_arrow_trianglehead_counterclockwise,
            _30_arrow_trianglehead_clockwise,
            _30_arrow_trianglehead_counterclockwise,
            _45_arrow_trianglehead_clockwise,
            _45_arrow_trianglehead_counterclockwise,
            _60_arrow_trianglehead_clockwise,
            _60_arrow_trianglehead_counterclockwise,
            _75_arrow_trianglehead_clockwise,
            _75_arrow_trianglehead_counterclockwise,
            _90_arrow_trianglehead_clockwise,
            _90_arrow_trianglehead_counterclockwise,
            arrow_trianglehead_clockwise,
            arrow_trianglehead_counterclockwise,
            arrow_trianglehead_rectanglepath,
            backward,
            backward_circle,
            backward_circle_fill,
            backward_end,
            backward_end_alt,
            backward_end_alt_fill,
            backward_end_circle,
            backward_end_circle_fill,
            backward_end_fill,
            backward_fill,
            backward_frame,
            backward_frame_fill,
            checkmark_arrow_trianglehead_counterclockwise,
            forward,
            forward_circle,
            forward_circle_fill,
            forward_end,
            forward_end_alt,
            forward_end_alt_fill,
            forward_end_circle,
            forward_end_circle_fill,
            forward_end_fill,
            forward_fill,
            forward_frame,
            forward_frame_fill,
            house_badge_exclamationmark,
            house_badge_exclamationmark_fill,
            infinity,
            infinity_circle,
            infinity_circle_fill,
            minus_arrow_trianglehead_counterclockwise,
            music_note_house,
            music_note_house_fill,
            pause,
            pause_circle,
            pause_circle_fill,
            pause_fill,
            pause_rectangle,
            pause_rectangle_fill,
            play,
            play_circle,
            play_circle_fill,
            play_fill,
            play_house,
            play_house_fill,
            play_rectangle,
            play_rectangle_fill,
            play_slash,
            play_slash_fill,
            play_square,
            play_square_fill,
            play_square_stack,
            play_square_stack_fill,
            playpause,
            playpause_circle,
            playpause_circle_fill,
            playpause_fill,
            plus_arrow_trianglehead_clockwise,
            record_circle,
            record_circle_fill,
            _repeat,
            repeat_1,
            repeat_1_circle,
            repeat_1_circle_fill,
            repeat_circle,
            repeat_circle_fill,
            shuffle,
            shuffle_circle,
            shuffle_circle_fill,
            stop,
            stop_circle,
            stop_circle_fill,
            stop_fill,
            text_append,
            text_insert,
            text_line_first_and_arrowtriangle_forward,
            text_line_last_and_arrowtriangle_forward
        ]
    }
}
